Todo list
MaratSan/my-app pull request #1
Opened 2023-12-04 22:46 UTC by MaratSan

pls check

2023-12-04 23:46 UTC, sagmi reviewed
Если смотреть в целом, работа пиздатая, но есть ошибки:
В конце файлов отсутствует пустая срока (для гита это важно)
В некоторых местах отсутвует табуляция
Нарушена логика кода - где хранилище, там и действия (функции) над этим хранилищем
Импорты должны отталкиваться от своего местонахождения
Если происходит какая-то модификация данных (в данном случае добавление новой тудушки), должно быть в форме - если у пользователя отключен js, запрос пойдет на сервер

Но это все небольшие ошибки
Работа пиздатая
Оценка: **8,5/10**

2023-12-04 23:46 UTC, sagmi commented on src/index.jsx
> +import Home from '../src/components/screens/Home/Home';
Неправильный импорт
Не нужно выходить из дирктории (../src), можно просто import Home from './components/screens/Home/Home';
Ниже с Layout сделано правильно
Возможно это автоимпорт VS code, но это нужно контролировать

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/item/TodoItem.jsx
> +
Лишняя пустая строка (увеличивает вес файла)

2023-12-04 23:46 UTC, sagmi commented on src/components/layout/Layout.jsx
> +export default Layout;
Отсутствует в конце пустая срока

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/Home.jsx
> +        setTodos ([...todos].filter(t=>t._id !== _id))
У стрелочных функций лучше использовать скобки, так код понятнее
const removeTodo = (_id) => {
        setTodos ([...todos].filter(t=>t._id !== _id))
}

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/Home.jsx
> +export default Home
Отсутствует в конце пустая срока

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/createTodoField/CreateTodoField.jsx
> +    }
Эту функцию лучше сделать в Home и пробрасывать сюда
Логика в том, что где создаешь хранилище, там и происходит работа с ними
Все последующие компоненты работают с этими функциями, а не создают логику для этого хранилища

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/createTodoField/CreateTodoField.jsx
> +export default CreateTodoField
Отсутствует в конце пустая срока

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/createTodoField/CreateTodoField.jsx
> +                onKeyPress={e => e.key === 'Enter' && addTodo(title)}
Это красиво сделано, но семантика рушится - лучше сделать это формой и повесить на onSubmit функцию addTodo

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/item/CheckBox.jsx
> +export default CheckBox;
Отсутствует в конце пустая срока

2023-12-04 23:46 UTC, sagmi commented on src/components/screens/Home/item/TodoItem.jsx
> +export default TodoItem
Отсутствует в конце пустая срока

2023-12-05 16:37 UTC, MaratSan reviewed
pls check

2023-12-05 17:57 UTC, sagmi requested changes
Доделай и все супер
**Красавчик!**

2023-12-05 17:57 UTC, sagmi commented on src/components/screens/Home/createTodoField/CreateTodoField.jsx
>      }
Эта функция должна быть около хранилища (в Home), а сюда пробрасываться
Т.е. функция
```
const addTodo = (todo) => {
    setTodos ([
             {
             _id: new Date(),
             todo,
             isCompleted: false,
             },
             ...todos
         ]);
}
```
должна быть в Home, а тут нужно создать функцию
```
const handleSubmit = (e) => {
        e.preventDefault();
        addTodo(title);
        setTitle("");
    }
```

2023-12-07 15:38 UTC, closed without merging